### PR TITLE
Pm 2 basic readme 01

### PR DESCRIPTION
**Pull request by brinkbrink**
This is for issue #2 but it is not complete.

### CODE REVIEW

**Review by brandondombrowsky — APPROVED** [review]
Omg I LOVE it! Did BC consult? It looks a lot like what he told me.

**Comment by Seiyaroo** [comment]
Lot more meat to this than the one I had, I like it. I think merging the two formats in some way might be our final goal. I like the overall form of this and simply think adding in the info from mine into an appropriate place would fit.

**Review by Seiyaroo — APPROVED** [review]
LGTM, pending response to my previous comment(s).

**Comment by brinkbrink** [comment]
Thanks, Nick! That sounds like a good idea to keep our repos nice and uniform!

**Comment by brinkbrink** [comment]
This was also to test my GPG key, looks like I hadn't configured it completely.

**Pull request merged**
